# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"7\n\x11\x45mbeddingResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x12\n\ndimensions\x18\x02 \x01(\x05\x32]\n\x10\x45mbeddingService\x12I\n\x0cGetEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=30
  _globals['_EMBEDDINGREQUEST']._serialized_end=62
  _globals['_EMBEDDINGRESPONSE']._serialized_start=64
  _globals['_EMBEDDINGRESPONSE']._serialized_end=119
  _globals['_EMBEDDINGSERVICE']._serialized_start=121
  _globals['_EMBEDDINGSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
