# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"!\n\x10RecognizeRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\";\n\nTextResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0b\n\x03\x62ox\x18\x03 \x03(\x02\"5\n\x11RecognizeResponse\x12 \n\x07results\x18\x01 \x03(\x0b\x32\x0f.ocr.TextResult2H\n\nOCRService\x12:\n\tRecognize\x12\x15.ocr.RecognizeRequest\x1a\x16.ocr.RecognizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZEREQUEST']._serialized_start=18
  _globals['_RECOGNIZEREQUEST']._serialized_end=51
  _globals['_TEXTRESULT']._serialized_start=53
  _globals['_TEXTRESULT']._serialized_end=112
  _globals['_RECOGNIZERESPONSE']._serialized_start=114
  _globals['_RECOGNIZERESPONSE']._serialized_end=167
  _globals['_OCRSERVICE']._serialized_start=169
  _globals['_OCRSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
