# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"0\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x02\"8\n\x12SynthesizeResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x32K\n\nTTSService\x12=\n\nSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=18
  _globals['_SYNTHESIZEREQUEST']._serialized_end=66
  _globals['_SYNTHESIZERESPONSE']._serialized_start=68
  _globals['_SYNTHESIZERESPONSE']._serialized_end=124
  _globals['_TTSSERVICE']._serialized_start=126
  _globals['_TTSSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
